### ISSUE TITLE
Tenho um pedido a fazer 👍 

### ISSUE THREAD

**Issue by LucasIsMartins** [thebitnomad/DayBreak-GMTools#1]
Primeiramente gostaria de dizer que fico muito feliz por ter disponibilizado o código fonte desse joguinho maravilhoso, joguei muito e com certeza queria jogar mais, pra mim o melhor que joguei na vida , dito isto gostaria de perguntar se vão disponibilizar a documentação ou quem sabe um tutorial passo a passo em pdf msm de como proceder com os arquivos para que mesmo que de forma improvisada conissigamos ligar um server na nossa maquina e matar a saudade. Sou formado na area mas olhando os arquivos do repositório fiquei todo perdido haha. Grato pela atenção.

**Comment by thebitnomad** [comment]
Olá Lucas!

A documentação vai sair, estou organizando os docs. em breve espero ver servidores privados de DayBreak online por ai 💯 
Os repositórios existentes são basicamente os arquivos brutos extraídos de cada servidor do DayBreak.
Eram 4 servidores no total, 1 Windows Server 2003 "GM Tools que rodava IIS" e 3 servidores CentOs 5.10

Hoje, acredito que podemos fazer tudo em apenas 1 maquina com Windows 10/11 + WSL Fedora.
