### ISSUE TITLE
issues about EXTJS !

### ISSUE THREAD

**Issue by thanhle19921993** [thebitnomad/DayBreak-GMTools#2]
hello sir !! 
i did have prolems about EXTJS and i did  try to find them in webmaster source and i couldnt find them !! plz help me !! thank a lot !! 
[
![image](https://github.com/thebitnomad/DayBreak-GMTools/assets/111475652/e4524d6d-6335-4152-8bbf-a508abad36bb)
](url)

**Comment by thanhle19921993** [comment]
plz! plz help me

**Comment by thanhle19921993** [comment]
plz ! game master!

**Comment by thebitnomad** [comment]
Problem solved.
